// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Serwis_pogodowy_GUI;

#nullable disable

namespace Serwis_pogodowy_GUI.Migrations
{
    [DbContext(typeof(BazaPogoda))]
    partial class BazaPogodaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Serwis_pogodowy_GUI.Pogoda_inicjalizuj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("cisnienie")
                        .HasColumnType("REAL");

                    b.Property<string>("miasto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("temperatura")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("PogodaInicjalizuj");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            cisnienie = 959.0,
                            miasto = "Warszawa",
                            temperatura = 20.0
                        },
                        new
                        {
                            Id = 2,
                            cisnienie = 965.0,
                            miasto = "Gdańsk",
                            temperatura = 18.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
